spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/bookstoreapi_clients
    password: jackson1403
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: 'true'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
  application:
    name: clients-api
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
